/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class DataBarang extends javax.swing.JPanel {
    DefaultTableModel model;
    /**
     * Creates new form DataBarang
     */
    public DataBarang() {
        initComponents();
        
        Object[] header ={"","No","Nama","Harga","Kategori","stok", "Diskon"};
        model = new DefaultTableModel(header, 0);
        jTable1.setModel(model);
        
        //heading index dimysql n ketika di view ntar tdk ada
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        
        //mmbuat agar kolom nomor tdk terlalu lebar
        jTable1.getColumnModel().getColumn(1).setMinWidth(80);
        jTable1.getColumnModel().getColumn(1).setMaxWidth(80);
        
        //agar tdk sempit di tabelnya
        jTable1.setRowHeight(30);
        loadData("");
    }
    
     private void loadData(String key){
        
        try {
            model.setRowCount(0); //menghapus data scra keseluruhan n diisi dg perintah yg baru
            
            String where = !key.isEmpty() ? "WHERE nama_barang LIKE '%"+key+"%' OR harga LIKE '%"+key+"%' OR kategori LIKE '%"+key+"%' OR stok LIKE '%"+key+"%' OR diskon LIKE '%"+key+"%' " : ""; //melakukan pengecekan
            String q = "SELECT * FROM barang " +where;
            //pembuatan koneksi
            Connection c = Koneksi.MySQL();
            Statement st = c.createStatement();
            ResultSet rs = st.executeQuery(q);
            int nomor = 0;
            while (rs.next()) {
                int id = rs.getInt("id_barang");
                String nama = rs.getString("nama_barang");
                String harga = rs.getString("harga");
                String kategori = rs.getString("kategori");
                String stok = rs.getString("stok");
                String diskon = rs.getString("diskon");
                nomor++;
                Object[] data = {id,nomor, nama, harga, kategori, stok, diskon};
                model.addRow(data);
                
            }
            
        } catch (Exception e) {
            //utk mnnngkap eror
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));

        btnTambah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(204, 204, 255));
        btnHapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jLabel1.setText("Cari");

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUbah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(55, 55, 55)
                .addComponent(btnTambah)
                .addGap(18, 18, 18)
                .addComponent(btnUbah)
                .addGap(27, 27, 27)
                .addComponent(btnHapus)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_END);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(250, 250));
        jScrollPane1.setName(""); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
       HalamanUtama.panggilPanel(new TambahBarang());
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        int baris = jTable1.getSelectedRow();
        if(baris != -1){
            int id = Integer.parseInt(jTable1.getValueAt(baris, 0).toString());
            String nama = jTable1.getValueAt(baris, 2).toString();
            String harga = jTable1.getValueAt(baris, 3).toString();
            String kategori = jTable1.getValueAt(baris, 4).toString();
            String stok = jTable1.getValueAt(baris, 5).toString();
            String diskon = jTable1.getValueAt(baris, 5).toString();
            Barang s = new  Barang();
            s.setId(id);
            s.setNama(nama);
            s.setHarga(harga);
            s.setKategori(kategori);
            s.setStok(stok);
            s.setDiskon(diskon);
            HalamanUtama.panggilPanel(new UbahBarang(s));
            
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
         // utk mnghapus yg dideteksi index dulu
        int baris = jTable1.getSelectedRow();
        if(baris != -1){
            //JOptionPane.showMessageDialog(this, baris); //ini igunakan urk melihat index jadi td berpengaruh
            int pilih = JOptionPane.showConfirmDialog(this, 
                    "Apakah anda yakin?", "Konfirmasi", 
                    JOptionPane.YES_NO_OPTION);
            if(pilih == 0){
                //hapus data
                try {
                    Connection c = Koneksi.MySQL();
                    Statement st = c.createStatement();
                    
                    Object oid = jTable1.getValueAt(baris, 0); //utk mndpatkan nialai pd index ke bari n kolom ke 0 return value brupa object hasilnya
                    String strid = oid.toString(); //untk mngkon versi objec ke string
                    int id = Integer.parseInt(strid); //utk konversi string ke int
                    String q = "DELETE FROM barang WHERE id_barang="+id+"";
                    st.executeUpdate(q);
                    
                    //utk refrest data
                    loadData("");
                    //utk pesan bahwa data sudah di hapus
                    JOptionPane.showMessageDialog(this, "Data telah dihapus!");
                    
                } catch (SQLException | NumberFormatException | HeadlessException e) {
                }
                
            }else if(pilih == 1){ //boleh langsusng mnggunakan else if atau else
                jTable1.clearSelection();
                
                
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        String key = txtCari.getText();
        if(key.isEmpty()){
            loadData("");
        }else{
            loadData(key);
        }
    }//GEN-LAST:event_txtCariKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
